# Generated by Django 3.1.7 on 2021-04-02 06:22

import audio_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploadedtime', models.DateTimeField(validators=[audio_files.models.validate_datetime])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
