# Generated by Django 3.1.7 on 2021-04-02 08:40

import audio_files.customfield
import audio_files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_files', '0002_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('uploadedtime', models.DateTimeField(validators=[audio_files.models.validate_datetime])),
                ('author', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=audio_files.customfield.CommaSeparatedValuesField(blank=True, null=True, validators=[audio_files.models.validate_participants]),
        ),
    ]
